import { Doctor } from './types';

export const DOCTORS: Partial<Doctor>[] = [
  {
    doctor_id: "1",
    full_name: "Dr. Aruni Perera",
    slmc_number: "SLMC-MD-5432",
    specialty: "Cardiologist",
    gender: "Female",
    department_type: "Private",
    working_hospital: "National Hospital Colombo",
    contact_email: "aruni.p@prodoc.lk",
    years_of_experience: "12",
    image_url: "Dr.Aruni.jpeg",
    associated_hospitals: '[{"name":"Asiri Central Hospital","type":"Private"}]',
    bio: "Dr. Aruni Perera is a dedicated cardiologist specializing in the prevention, diagnosis, and management of heart diseases. With a strong focus on patient education and lifestyle-based interventions, she provides comprehensive cardiac care including hypertension management, heart failure treatment, and preventive cardiology. She is committed to promoting long-term heart health through evidence-based practice.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Mon, Wed",
    educational_qualifications: "MBBS, MD (Cardiology), Board Certified Cardiologist, Fellowship in Interventional Cardiology"
  },
  {
    doctor_id: "2",
    full_name: "Dr. Mohamed Fazil",
    slmc_number: "SLMC-MD-8812",
    specialty: "Neurologist",
    gender: "Male",
    department_type: "Both",
    working_hospital: "Asiri Central Hospital",
    contact_email: "fazil.m@prodoc.lk",
    years_of_experience: "8",
    image_url: "Dr.Mohamed.jpeg",
    associated_hospitals: '[{"name":"Asiri Central Hospital","type":"Private"},{"name":"Lady Ridgeway Hospital","type":"Government"}]',
    bio: "Dr. Mohamed Fazil is an experienced neurologist with expertise in treating disorders of the brain, spine, and nervous system. He manages conditions such as epilepsy, stroke, migraines, and neurodegenerative diseases. His patient-centered approach ensures thorough evaluation and personalized treatment plans.",
    languages: "English, Tamil, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Neurology), Diploma in Clinical Neurophysiology"
  },
  {
    doctor_id: "3",
    full_name: "Dr. Sandali Jayasuriya",
    slmc_number: "SLMC-MD-3301",
    specialty: "Pediatrician",
    gender: "Female",
    department_type: "Government",
    working_hospital: "Colombo, Sri Lanka",
    contact_email: "sandali.j@prodoc.lk",
    years_of_experience: "15",
    image_url: "Dr.Sandali.jpeg",
    associated_hospitals: '[{"name":"Lady Ridgeway Hospital","type":"Government"},{"name":"Kandy General Hospital","type":"Government"}]',
    bio: "Dr. Sandali Jayasuriya is a compassionate pediatrician devoted to the health and wellbeing of infants, children, and adolescents. She provides preventive care, immunizations, growth monitoring, and treatment for common childhood illnesses while building trusting relationships with families.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Mon,Thu,Sat",
    educational_qualifications: "MBBS, MD (Pediatrics), Fellowship in Neonatology"
  },
  {
    doctor_id: "4",
    full_name: "Dr. Kamal Gunawardena",
    slmc_number: "SLMC-MD-9921",
    specialty: "Orthopedic Surgeon",
    gender: "Male",
    department_type: "Both",
    working_hospital: "Kandy General Hospital",
    contact_email: "kamal.g@prodoc.lk",
    years_of_experience: "20",
    image_url: "Dr.Kamal.jpeg",
    associated_hospitals: '[{"name":"Kandy General Hospital","type":"Government"},{"name":"Nawaloka Hospital","type":"Private"}]',
    bio: "Dr. Kamal Gunawardena specializes in diagnosing and surgically treating musculoskeletal conditions. His expertise includes joint replacements, sports injuries, fracture management, and spinal disorders. He is committed to restoring mobility and improving quality of life for his patients.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MS (Orthopedic Surgery), FRCS (UK)"
  },
  {
    doctor_id: "5",
    full_name: "Dr. Ishani de Silva",
    slmc_number: "SLMC-MD-4456",
    specialty: "Dermatologist",
    gender: "Female",
    department_type: "Both",
    working_hospital: "Nawaloka Hospital",
    contact_email: "ishani.ds@prodoc.lk",
    years_of_experience: "5",
    image_url: "Dr.Ishani.jpeg",
    associated_hospitals: '[{"name":"Nawaloka Hospital","type":"Private"},{"name":"NIMH Hospital","type":"Government"}]',
    bio: "Dr. Ishani de Silva is a skilled dermatologist focused on treating skin, hair, and nail conditions. She manages acne, eczema, psoriasis, and skin infections while also offering cosmetic dermatology services. Her holistic approach promotes healthy and confident skin.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Mon, Wed, Fri",
    educational_qualifications: "MBBS, MD (Dermatology)"
  },
  {
    doctor_id: "6",
    full_name: "Dr. Tharindu Wickramasinghe",
    slmc_number: "SLMC-MD-7723",
    specialty: "Psychiatrist",
    gender: "Male",
    department_type: "Both",
    working_hospital: "NIMH Angoda",
    contact_email: "tharindu.w@prodoc.lk",
    years_of_experience: "10",
    image_url: "Dr.Tharindu.jpeg",
    associated_hospitals: '[{"name":"NIMH Angoda","type":"Government"},{"name":"Durdans Hospital","type":"Private"}]',
    bio: "Dr. Tharindu Wickramasinghe is a consultant psychiatrist dedicated to supporting mental health across all age groups. He treats anxiety disorders, depression, mood disorders, and stress-related conditions using evidence-based therapies and medication management in a compassionate environment.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Thu,Fri",
    educational_qualifications: "MBBS, MD (Psychiatry)"
  },
  {
    doctor_id: "7",
    full_name: "Dr. Niroshini Wijesinghe",
    slmc_number: "SLMC-MD-1122",
    specialty: "General Physician",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Durdans Hospital",
    contact_email: "niro.w@prodoc.lk",
    years_of_experience: "7",
    image_url: "Dr.Niroshini.jpeg",
    associated_hospitals: '[{"name":"Durdans Hospital","type":"Private"},{"name":"Leesons Hospital","type":"Private"}]',
    bio: "Dr. Niroshini Wijesinghe is an experienced general physician providing comprehensive primary care services. She manages chronic conditions such as diabetes and hypertension, conducts routine health screenings, and ensures coordinated care for her patients.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Sat,Sun",
    educational_qualifications: "MBBS, MD (Internal Medicine)"
  },
  {
    doctor_id: "8",
    full_name: "Dr. Janith Perera",
    slmc_number: "SLMC-MD-9000",
    specialty: "Neurologist",
    gender: "Male",
    department_type: "Both",
    working_hospital: "Lessons Hospital",
    contact_email: "janith@prodoc.lk",
    years_of_experience: "10",
    image_url: "Dr.Janith.jpeg",
    associated_hospitals: '[{"name":"Leesons Hospital","type":"Private"},{"name":"National Hospital","type":"Government"}]',
    bio: "Dr. Janith Perera is a neurologist with a special interest in stroke management and neuromuscular disorders. He utilizes advanced diagnostic techniques to develop tailored treatment strategies that improve neurological function and patient outcomes.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Neurology), Fellowship in Stroke Medicine"
  },
  {
    doctor_id: "9",
    full_name: "Dr. Anura Bandara",
    slmc_number: "SLMC-MD-2101",
    specialty: "Oncologist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Apeksha Hospital",
    contact_email: "anura.b@prodoc.lk",
    years_of_experience: "18",
    image_url: "Dr.Anura.jpeg",
    associated_hospitals: '[{"name":"National Hospital","type":"Government"},{"name":"Lanka Hospital","type":"Private"}]',
    bio: "Dr. Anura Bandara is a dedicated oncologist specializing in the diagnosis and treatment of various cancers. He works closely with multidisciplinary teams to provide chemotherapy, targeted therapy, and supportive cancer care with empathy and precision.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Clinical Oncology), Fellowship in Medical Oncology"
  },
  {
    doctor_id: "10",
    full_name: "Dr. Dilini Fernando",
    slmc_number: "SLMC-MD-3490",
    specialty: "Gynaecologist",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Lanka Hospitals",
    contact_email: "dilini.f@prodoc.lk",
    years_of_experience: "11",
    image_url: "Dr.Dilini.jpeg",
    associated_hospitals: '[{"name":"Lanka Hospitals","type":"Private"},{"name":"Eye Hospital Colombo","type":"Government"}]',
    bio: "Dr. Dilini Fernando is a compassionate gynaecologist offering comprehensive women’s healthcare services. She provides antenatal care, fertility guidance, menstrual disorder management, and minimally invasive gynecological procedures.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Obstetrics & Gynaecology)"
  },
  {
    doctor_id: "11",
    full_name: "Dr. Rohan Abeysekera",
    slmc_number: "SLMC-MD-5566",
    specialty: "Ophthalmologist",
    gender: "Male",
    department_type: "Both",
    working_hospital: "Eye Hospital Colombo",
    contact_email: "rohan.a@prodoc.lk",
    years_of_experience: "22",
    image_url: "Dr.Rohan.jpeg",
    associated_hospitals: '[{"name":"Eye Hospital","type":"Government"},{"name":"Hemas Hospital","type":"Private"}]',
    bio: "Dr. Rohan Abeysekera is an ophthalmologist specializing in the diagnosis and surgical treatment of eye disorders. His expertise includes cataract surgery, glaucoma management, and diabetic eye care, ensuring clear vision and long-term eye health.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MS (Ophthalmology), Fellowship in Retina/Cornea"
  },
  {
    doctor_id: "12",
    full_name: "Dr. Harshana Weerasinghe",
    slmc_number: "SLMC-MD-1289",
    specialty: "ENT Surgeon",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Karapitiya Teaching Hospital",
    contact_email: "harshana.w@prodoc.lk",
    years_of_experience: "9",
    image_url: "Dr.Harshana.jpeg",
    associated_hospitals: '[{"name":"Karapitiya Teaching Hospital","type":"Government"},{"name":"Kings Hospital","type":"Private"}]',
    bio: "Dr. Harshana Weerasinghe is an experienced ENT surgeon managing ear, nose, and throat conditions. He performs procedures for sinus disorders, tonsillitis, hearing problems, and voice-related issues with precision and patient-focused care.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MS (ENT Surgery)"
  },
  {
    doctor_id: "13",
    full_name: "Dr. Priyantha Silva",
    slmc_number: "SLMC-MD-8832",
    specialty: "Urologist",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Kings Hospital",
    contact_email: "priyantha.s@prodoc.lk",
    years_of_experience: "14",
    image_url: "Dr.Priyantha.jpeg",
    associated_hospitals: '[{"name":"Kings Hospital","type":"Private"},{"name":"TH Peradeniya Hospital","type":"Government"}]',
    bio: "Dr. Priyantha Silva specializes in diagnosing and treating urinary tract and male reproductive system disorders. He manages kidney stones, prostate conditions, and urinary infections using both medical and minimally invasive surgical techniques.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Mon,Fri,Sun",
    educational_qualifications: "MBBS, MS (Urology)"
  },
  {
    doctor_id: "14",
    full_name: "Dr. Nilumi Rathnayake",
    slmc_number: "SLMC-MD-4402",
    specialty: "Endocrinologist",
    gender: "Female",
    department_type: "Government",
    working_hospital: "TH Peradeniya",
    contact_email: "nilumi.r@prodoc.lk",
    years_of_experience: "6",
    image_url: "Dr.Nilumi.jpeg",
    associated_hospitals: '[{"name":"TH Peradeniya","type":"Government"},{"name":"Hemas Hospital","type":"Private"}]',
    bio: "Dr. Nilumi Rathnayake is an endocrinologist focusing on hormonal and metabolic disorders. She provides expert care for diabetes, thyroid diseases, osteoporosis, and adrenal conditions, emphasizing long-term disease management.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Wed,Thu",
    educational_qualifications: "MBBS, MD (Endocrinology)"
  },
  {
    doctor_id: "15",
    full_name: "Dr. Saman Kumara",
    slmc_number: "SLMC-MD-9111",
    specialty: "Rheumatologist",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Hemas Hospital",
    contact_email: "saman.k@prodoc.lk",
    years_of_experience: "13",
    image_url: "Dr.Saman.jpeg",
    associated_hospitals: '[{"name":"Hemas Hospital","type":"Private"},{"name":"Jayewardenepura Hospital ","type":"Government"}]',
    bio: "Dr. Saman Kumara is a rheumatologist specializing in autoimmune and inflammatory joint diseases. He treats arthritis, lupus, gout, and connective tissue disorders, helping patients maintain mobility and reduce pain.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Rheumatology)"
  },
  {
    doctor_id: "16",
    full_name: "Dr. Duminda Wijesekara",
    slmc_number: "SLMC-MD-2022",
    specialty: "Nephrologist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Jayewardenepura Hospital",
    contact_email: "duminda.w@prodoc.lk",
    years_of_experience: "16",
    image_url: "Dr.Duminda.jpeg",
    associated_hospitals: '[{"name":"Jayewardenepura Hospital","type":"Government"},{"name":"Nawaloka Hospital ","type":"Private"}]',
    bio: "Dr. Duminda Wijesekara is a nephrologist dedicated to kidney health. He manages chronic kidney disease, dialysis care, electrolyte disorders, and hypertension-related kidney complications with a comprehensive approach.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Nephrology)"
  },
  {
    doctor_id: "17",
    full_name: "Dr. Sajani Alwis",
    slmc_number: "SLMC-MD-3033",
    specialty: "Radiologist",
    gender: "Female",
    department_type: "Both",
    working_hospital: "Nawaloka Hospital",
    contact_email: "sajani.a@prodoc.lk",
    years_of_experience: "10",
    image_url: "Dr.Sajani.jpeg",
    associated_hospitals: '[{"name":"Nawaloka Hospital","type":"Private"},{"name":"Kurunegala Teaching Hospital ","type":"Government"}]',
    bio: "Dr. Sajani Alwis is a consultant radiologist specializing in diagnostic imaging, including ultrasound, CT, MRI, and X-ray interpretation. She plays a critical role in accurate diagnosis and collaborative patient management.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Radiology), Fellowship in Imaging"
  },
  {
    doctor_id: "18",
    full_name: "Dr. Gayan Edirisinghe",
    slmc_number: "SLMC-MD-4044",
    specialty: "Anesthesiologist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Kurunegala Teaching Hospital",
    contact_email: "gayan.e@prodoc.lk",
    years_of_experience: "12",
    image_url: "Dr.Gayan.jpeg",
    associated_hospitals: '[{"name":"Kurunegala Teaching Hospital","type":"Government"},{"name":"Asiri Central Hospital ","type":"Private"}]',
    bio: "Dr. Gayan Edirisinghe is an anesthesiologist skilled in perioperative care, pain management, and critical care support. He ensures patient safety and comfort before, during, and after surgical procedures.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Anaesthesiology)"
  },
  {
    doctor_id: "19",
    full_name: "Dr. Maheshi Fonseka",
    slmc_number: "SLMC-MD-5055",
    specialty: "Gastroenterologist",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Central Hospital",
    contact_email: "maheshi.f@prodoc.lk",
    years_of_experience: "8",
    image_url: "Dr.Maheshi.jpeg",
    associated_hospitals: '[{"name":"Asiri Central Hospital","type":"Private"},{"name":"Welisara Chest Hospital","type":"Government"}]',
    bio: "Dr. Maheshi Fonseka specializes in digestive health, managing conditions such as acid reflux, liver disease, inflammatory bowel disease, and gastrointestinal infections. She also performs diagnostic endoscopic procedures.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Thu",
    educational_qualifications: "MBBS, MD (Gastroenterology)"
  },
  {
    doctor_id: "20",
    full_name: "Dr. Buddhika Senaratne",
    slmc_number: "SLMC-MD-6066",
    specialty: "Pulmonologist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Welisara Chest Hospital",
    contact_email: "buddhika.s@prodoc.lk",
    years_of_experience: "19",
    image_url: "Dr.Buddhika.jpeg",
    associated_hospitals: '[{"name":"Welisara Chest Hospital","type":"Government"},{"name":"Nawaloka Hospital ","type":"Private"}]',
    bio: "Dr. Buddhika Senaratne is a pulmonologist focused on respiratory disorders including asthma, COPD, pneumonia, and sleep apnea. He emphasizes preventive lung care and patient education.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Respiratory Medicine)"
  },
  {
    doctor_id: "21",
    full_name: "Dr. Lakmal Perera",
    slmc_number: "SLMC-MD-1111",
    specialty: "Cardiologist",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Nawaloka Hospital",
    contact_email: "lakmal@prodoc.lk",
    years_of_experience: "14",
    image_url: "Dr.Lakmal.jpeg",
    associated_hospitals: '[{"name":"Nawaloka Hospital","type":"Private"},{"name":"Panadura Base Hospital ","type":"Government"}]',
    bio: "Dr. Lakmal Perera is a cardiologist with expertise in interventional cardiology and cardiac risk assessment. He provides advanced diagnostic testing and minimally invasive procedures to treat coronary artery disease.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Cardiology), Fellowship in Echocardiography"
  },
  {
    doctor_id: "22",
    full_name: "Dr. Surani Gomes",
    slmc_number: "SLMC-MD-2222",
    specialty: "Pediatrician",
    gender: "Female",
    department_type: "Government",
    working_hospital: "Panadura Base Hospital",
    contact_email: "surani@prodoc.lk",
    years_of_experience: "9",
    image_url: "Dr.Surani.jpeg",
    associated_hospitals: '[{"name":"Panadura Base Hospital","type":"Government"},{"name":"Lady Ridgeway Hospital ","type":"Government"}]',
    bio: "Dr. Surani Gomes is a pediatrician dedicated to child development and preventive healthcare. She offers immunization programs, nutritional counseling, and management of acute and chronic pediatric conditions.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Wed,Sat,Sun",
    educational_qualifications: "MBBS, MD (Pediatrics)"
  },
  {
    doctor_id: "23",
    full_name: "Dr. Ruwan Fernando",
    slmc_number: "SLMC-MD-3333",
    specialty: "General Surgeon",
    gender: "Male",
    department_type: "Both",
    working_hospital: "Negombo General Hospital",
    contact_email: "ruwan@prodoc.lk",
    years_of_experience: "17",
    image_url: "Dr.Ruwan.jpeg",
    associated_hospitals: '[{"name":"Negombo General Hospital","type":"Government"},{"name":"Medihelp Hospital ","type":"Private"}]',
    bio: "Dr. Ruwan Fernando is a skilled general surgeon performing a wide range of surgical procedures including abdominal surgeries, hernia repair, and minimally invasive laparoscopic interventions.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MS (General Surgery), FRCS"
  },
  {
    doctor_id: "24",
    full_name: "Dr. Nadeeka Silva",
    slmc_number: "SLMC-MD-4444",
    specialty: "Dermatologist",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Medihelp Hospital",
    contact_email: "nadeeka@prodoc.lk",
    years_of_experience: "4",
    image_url: "Dr.Nadeeka.jpeg",
    associated_hospitals: '[{"name":"Medihelp Hospital","type":"Private"},{"name":"Mulleriyawa Hospital ","type":"Government"}]',
    bio: "Dr. Nadeeka Silva is a dermatologist specializing in both medical and aesthetic skin care. She treats chronic skin conditions while offering advanced cosmetic procedures tailored to individual patient needs.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Mon,Wed",
    educational_qualifications: "MBBS, MD (Dermatology)"
  },
  {
    doctor_id: "25",
    full_name: "Dr. Sanjeewa Munasinghe",
    slmc_number: "SLMC-MD-5555",
    specialty: "Psychiatrist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Mulleriyawa Hospital",
    contact_email: "sanjeewa.m@prodoc.lk",
    years_of_experience: "6",
    image_url: "Dr.Sanjeewa.jpeg",
    associated_hospitals: '[{"name":"Mulleriyawa Hospital","type":"Government"},{"name":"Fernandez Clinic ","type":"Private"}]',
    bio: "Dr. Sanjeewa Munasinghe is a consultant psychiatrist specializing in the diagnosis and management of mood disorders, anxiety conditions, and complex psychiatric illnesses. He adopts a holistic approach that integrates psychotherapy, medication management, and lifestyle guidance to promote long-term mental wellbeing.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Psychiatry)"
  },
  {
    doctor_id: "26",
    full_name: "Dr. Kaveesha Amarasinghe",
    slmc_number: "SLMC-MD-6666",
    specialty: "Gynaecologist",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Fernandez Clinic",
    contact_email: "kaveesha.a@prodoc.lk",
    years_of_experience: "8",
    image_url: "Dr.Kaveesha.jpeg",
    associated_hospitals: '[{"name":"Fernandez Clinic","type":"Private"},{"name":"Sugathadasa Institute ","type":"Government"}]',
    bio: "Dr. Kaveesha Amarasinghe provides comprehensive women’s healthcare, including antenatal care, fertility evaluation, and management of hormonal and menstrual disorders. She is committed to delivering compassionate, patient-centered care at every stage of a woman’s life.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Obstetrics & Gynaecology)"
  },
  {
    doctor_id: "27",
    full_name: "Dr. Vishwa Govindasamy",
    slmc_number: "SLMC-MD-7777",
    specialty: "Sports Medicine Physician",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Sugathadasa Institute",
    contact_email: "vishwa.g@prodoc.lk",
    years_of_experience: "5",
    image_url: "Dr.Vishwa.jpeg",
    associated_hospitals: '[{"name":"Golden Key Hospital","type":"Private"},{"name":"Kalubowila Hospital ","type":"Government"}]',
    bio: "Dr. Vishwa Govindasamy specializes in sports-related injuries, performance optimization, and rehabilitation. He works closely with athletes and active individuals to prevent injuries, enhance recovery, and safely return patients to peak performance.",
    languages: "English, Tamil, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MS (Sports Medicine), Diploma in Sports Medicine"
  },
  {
    doctor_id: "28",
    full_name: "Dr. Malindu Jayawardena",
    slmc_number: "SLMC-MD-8888",
    specialty: "Orthopedic Surgeon",
    gender: "Male",
    department_type: "Both",
    working_hospital: "Kalubowila Hospital",
    contact_email: "malindu.j@prodoc.lk",
    years_of_experience: "21",
    image_url: "Dr.Malindu.jpeg",
    associated_hospitals: '[{"name":"Kalubowila Hospital","type":"Government"},{"name":"Leesons Hospital ","type":"Private"}]',
    bio: "Dr. Malindu Jayawardena is an orthopedic surgeon with expertise in joint reconstruction, trauma surgery, and arthroscopic procedures. His goal is to restore mobility and reduce pain through advanced surgical and non-surgical treatments.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Wed,Fri",
    educational_qualifications: "MBBS, MS (Orthopedic Surgery), Fellowship in Arthroscopy"
  },
  {
    doctor_id: "29",
    full_name: "Dr. Upul Samaratunga",
    slmc_number: "SLMC-MD-9999",
    specialty: "General Practitioner",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Matara General Hospital",
    contact_email: "upul.s@prodoc.lk",
    years_of_experience: "15",
    image_url: "Dr.Upul.jpeg",
    associated_hospitals: '[{"name":"Matara General Hospital","type":"Government"},{"name":"Golden Key Hospital ","type":"Private"}]',
    bio: "Dr. Upul Samaratunga is a trusted general practitioner offering primary healthcare services for patients of all ages. He focuses on preventive care, early diagnosis, and chronic disease management to support long-term health.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Family Medicine)"
  },
  {
    doctor_id: "30",
    full_name: "Dr. Ravindra Karunathilaka",
    slmc_number: "SLMC-MD-1010",
    specialty: "Cardiologist",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Golden Key Hospital",
    contact_email: "ravindra.k@prodoc.lk",
    years_of_experience: "25",
    image_url: "Dr.Ravindra.jpeg",
    associated_hospitals: '[{"name":"Golden Key Hospital","type":"Private"},{"name":"Kandy General Hospital ","type":"Government"}]',
    bio: "Dr. Ravindra Karunathilaka specializes in the diagnosis and treatment of cardiovascular diseases, including coronary artery disease and heart rhythm disorders. He emphasizes preventive cardiology and advanced cardiac diagnostics.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Fri,Sat",
    educational_qualifications: "MBBS, MD (Cardiology), FRCP (UK), Senior Consultant"
  },
  {
    doctor_id: "31",
    full_name: "Dr. Duminda Kalutota",
    slmc_number: "SLMC-MD-7002",
    specialty: "Cardiologist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Kandy General Hospital",
    contact_email: "duminda2.k@prodoc.lk",
    years_of_experience: "21",
    image_url: "Dr.Duminda2.jpeg",
    associated_hospitals: '[{"name":"Fernandez Clinic","type":"Private"},{"name":"TH Karapitiya Hospital ","type":"Government"}]',
    bio: "Dr. Duminda Kalutota is a cardiologist with a strong interest in heart failure management and cardiac imaging. He provides individualized treatment plans aimed at improving heart function and patient quality of life.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Cardiology), Fellowship in Electrophysiology"
  },
  {
    doctor_id: "32",
    full_name: "Dr. Kumudini Cooray",
    slmc_number: "SLMC-MD-7004",
    specialty: "Oncologist",
    gender: "Female",
    department_type: "Government",
    working_hospital: "TH Karapitiya",
    contact_email: "kumudini.c@prodoc.lk",
    years_of_experience: "10",
    image_url: "Dr.Kumudini.jpeg",
    associated_hospitals: '[{"name":"TH Karapitiya","type":"Government"},{"name":"Kings Hospital ","type":"Private"}]',
    bio: "Dr. Kumudini Cooray is an oncologist dedicated to delivering comprehensive cancer care. She combines chemotherapy, targeted therapy, and supportive treatments while guiding patients with empathy throughout their cancer journey.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Clinical Oncology)"
  },
  {
    doctor_id: "33",
    full_name: "Dr. Chandana Jayasundara",
    slmc_number: "SLMC-MD-7003",
    specialty: "Oncologist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Apeksha Hospital",
    contact_email: "chandana.j@prodoc.lk",
    years_of_experience: "14",
    image_url: "Dr.Chandana.jpeg",
    associated_hospitals: '[{"name":"Apeksha Hospital","type":"Government"},{"name":"Lanka Hospital ","type":"Private"}]',
    bio: "Dr. Chandana Jayasundara specializes in medical oncology, focusing on evidence-based cancer therapies and multidisciplinary care coordination to achieve the best possible outcomes for his patients.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Clinical Oncology)"
  },
  {
    doctor_id: "34",
    full_name: "Dr. Sharmila Perera",
    slmc_number: "SLMC-MD-7007",
    specialty: "Gynaecologist",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Lanka Hospitals",
    contact_email: "sharmila.p@prodoc.lk",
    years_of_experience: "16",
    image_url: "Dr.Sharmila.jpeg",
    associated_hospitals: '[{"name":"Lanka Hospitals","type":"Private"},{"name":"Asiri Central Hospital ","type":"Private"}]',
    bio: "Dr. Sharmila Perera offers expert care in obstetrics and gynecology, including high-risk pregnancy management and minimally invasive gynecological procedures.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Obstetrics & Gynaecology), Fellowship in Reproductive Medicine"
  },
  {
    doctor_id: "35",
    full_name: "Dr. Manoj Rathnayake",
    slmc_number: "SLMC-MD-7008",
    specialty: "Gynaecologist",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Asiri Central Hospital",
    contact_email: "manoj.r@prodoc.lk",
    years_of_experience: "13",
    image_url: "Dr.Manoj.jpeg",
    associated_hospitals: '[{"name":"Asiri Central Hospital","type":"Private"},{"name":"Durdans Hospital ","type":"Private"}]',
    bio: "Dr. Manoj Rathnayake provides comprehensive reproductive health services, fertility support, and surgical management of gynecological conditions with a patient-focused approach.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Obstetrics & Gynaecology)"
  },
  {
    doctor_id: "36",
    full_name: "Dr. Suresh Edirisinghe",
    slmc_number: "SLMC-MD-7009",
    specialty: "Neurologist",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Durdans Hospital",
    contact_email: "suresh.e@prodoc.lk",
    years_of_experience: "19",
    image_url: "Dr.Suresh.jpeg",
    associated_hospitals: '[{"name":"Durdans Hospital","type":"Private"},{"name":"Nawaloka Hospital ","type":"Private"}]',
    bio: "Dr. Suresh Edirisinghe specializes in treating epilepsy, stroke, and neuromuscular disorders. He utilizes advanced neurological assessments to deliver accurate diagnoses and effective treatments.",
    languages: "English, Sinhala, Tamil",
    second_opinion_available: "true",
    second_opinion_dates: "Tue, Thu, Fri",
    educational_qualifications: "MBBS, MD (Neurology), FRCP, Fellowship in Epileptology"
  },
  {
    doctor_id: "37",
    full_name: "Dr. Nilanthi Fernando",
    slmc_number: "SLMC-MD-7010",
    specialty: "Neurologist",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Nawaloka Hospital",
    contact_email: "nilanthi.f@prodoc.lk",
    years_of_experience: "11",
    image_url: "Dr.Nilanthi.jpeg",
    associated_hospitals: '[{"name":"Nawaloka Hospital","type":"Private"},{"name":"Kandy General Hospital ","type":"Government"}]',
    bio: "Dr. Nilanthi Fernando is a neurologist dedicated to managing headaches, multiple sclerosis, and degenerative neurological diseases with personalized care strategies.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Mon,Wed",
    educational_qualifications: "MBBS, MD (Neurology), Fellowship in Movement Disorders"
  },
  {
    doctor_id: "38",
    full_name: "Dr. Kamal Gunasekara",
    slmc_number: "SLMC-MD-9922",
    specialty: "Orthopedic Surgeon",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Kandy General Hospital",
    contact_email: "kamal2.g@prodoc.lk",
    years_of_experience: "19",
    image_url: "Dr.Kamal2.jpeg",
    associated_hospitals: '[{"name":"Kandy General Hospital","type":"Government"},{"name":"Golden Key Hospital ","type":"Private"}]',
    bio: "Dr. Kamal Gunasekara focuses on trauma surgery, spinal disorders, and joint replacement procedures, helping patients regain strength and mobility.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Thu,Sat",
    educational_qualifications: "MBBS, MS (Orthopedic Surgery)"
  },
  {
    doctor_id: "39",
    full_name: "Dr. Tharindu Wickrama",
    slmc_number: "SLMC-MD-7724",
    specialty: "Psychiatrist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "NIMH Angoda",
    contact_email: "tharindu2.w@prodoc.lk",
    years_of_experience: "11",
    image_url: "Dr.Tharindu2.jpeg",
    associated_hospitals: '[{"name":"NIMH Angoda","type":"Government"},{"name":"Durdans Hospital ","type":"Private"}]',
    bio: "Dr. Tharindu Wickrama provides compassionate psychiatric care for depression, anxiety, and stress-related disorders, combining therapy and pharmacological treatment approaches.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Mon,Fri,Sun",
    educational_qualifications: "MBBS, MD (Psychiatry)"
  },
  {
    doctor_id: "40",
    full_name: "Dr. Namal Wickramasinghe",
    slmc_number: "SLMC-MD-1021",
    specialty: "Neurologist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "National Hospital Colombo",
    contact_email: "namal.w@prodoc.lk",
    years_of_experience: "14",
    image_url: "Dr.Namal.jpeg",
    associated_hospitals: '[{"name":"National Hospital Colombo","type":"Government"},{"name":"Asiri Central Hospital ","type":"Private"}]',
    bio: "Dr. Namal Wickramasinghe has expertise in stroke prevention, cognitive disorders, and neurorehabilitation, offering comprehensive neurological care.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Neurology), Fellowship in Neuroimmunology"
  },
  {
    doctor_id: "41",
    full_name: "Dr. Shayani Wijesinghe",
    slmc_number: "SLMC-MD-1022",
    specialty: "Neurologist",
    gender: "Female",
    department_type: "Both",
    working_hospital: "Central Hospital",
    contact_email: "shayani.w@prodoc.lk",
    years_of_experience: "9",
    image_url: "Dr.Shayani.jpeg",
    associated_hospitals: '[{"name":"Asiri Central Hospital","type":"Private"},{"name":"Lanka Hospital ","type":"Private"}]',
    bio: "Dr. Shayani Wijesinghe specializes in pediatric and adult neurological conditions, providing thorough assessments and individualized treatment plans.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Neurology)"
  },
  {
    doctor_id: "42",
    full_name: "Dr. Ravi Hathurusinghe",
    slmc_number: "SLMC-MD-1023",
    specialty: "Oncologist",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Lanka Hospitals",
    contact_email: "ravi.h@prodoc.lk",
    years_of_experience: "22",
    image_url: "Dr.Ravi.jpeg",
    associated_hospitals: '[{"name":"Lanka Hospitals","type":"Private"},{"name":"Apeksha Hospital ","type":"Government"}]',
    bio: "Dr. Ravi Hathurusinghe delivers patient-centered oncology care, focusing on early cancer detection and innovative treatment strategies.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Clinical Oncology), FRCP"
  },
  {
    doctor_id: "43",
    full_name: "Dr. Sumudu Perera",
    slmc_number: "SLMC-MD-1024",
    specialty: "Oncologist",
    gender: "Female",
    department_type: "Both",
    working_hospital: "Apeksha Hospital",
    contact_email: "sumudu.p@prodoc.lk",
    years_of_experience: "13",
    image_url: "Dr.Sumudu.jpeg",
    associated_hospitals: '[{"name":"Apeksha Hospital","type":"Government"},{"name":"Medihelp Hospital ","type":"Private"}]',
    bio: "Dr. Sumudu Perera is dedicated to comprehensive cancer management, integrating modern therapies with supportive and palliative care services.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Fri,Sat",
    educational_qualifications: "MBBS, MD (Clinical Oncology)"
  },
  {
    doctor_id: "44",
    full_name: "Dr. Dinesh Gunasekera",
    slmc_number: "SLMC-MD-1025",
    specialty: "Dermatologist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "National Hospital Colombo",
    contact_email: "dinesh.g@prodoc.lk",
    years_of_experience: "11",
    image_url: "Dr.Dinesh.jpeg",
    associated_hospitals: '[{"name":"National Hospital Colombo","type":"Government"},{"name":"Medihelp Hospital ","type":"Private"}]',
    bio: "Dr. Anusha Ratnayake specializes in chronic skin disease management and aesthetic dermatology, focusing on skin health and patient confidence.",
    languages: "English, Sinhala, Tamil",
    second_opinion_available: "true",
    second_opinion_dates: "Mon,Wed,Sun",
    educational_qualifications: "MBBS, MD (Dermatology)"
  },
  {
    doctor_id: "45",
    full_name: "Dr. Anusha Ratnayake",
    slmc_number: "SLMC-MD-1026",
    specialty: "Dermatologist",
    gender: "Female",
    department_type: "Government",
    working_hospital: "Kandy General Hospital",
    contact_email: "anusha.r@prodoc.lk",
    years_of_experience: "16",
    image_url: "Dr.Anusha.jpeg",
    associated_hospitals: '[{"name":"Kandy General Hospital","type":"Government"},{"name":"Nawaloka Hospital ","type":"Private"}]',
    bio: "Dr. Dinesh Gunasekera treats a wide range of skin disorders including acne, psoriasis, and allergic skin conditions, offering both medical and cosmetic dermatology services.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Dermatology), Fellowship in Cosmetic Dermatology"
  },
  {
    doctor_id: "46",
    full_name: "Dr. Lasith Mudalige",
    slmc_number: "SLMC-MD-1029",
    specialty: "Psychiatrist",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Nawaloka Hospital",
    contact_email: "lasith.m@prodoc.lk",
    years_of_experience: "7",
    image_url: "Dr.Lasith.jpeg",
    associated_hospitals: '[{"name":"Nawaloka Hospital","type":"Private"},{"name":"Kings Hospital ","type":"Private"}]',
    bio: "Dr. Lasith Mudalige provides comprehensive mental health care, addressing mood disorders, behavioral issues, and stress-related conditions in a supportive environment.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Psychiatry)"
  },
  {
    doctor_id: "47",
    full_name: "Dr. Mihiri de Silva",
    slmc_number: "SLMC-MD-1030",
    specialty: "Psychiatrist",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Kings Hospital",
    contact_email: "mihiri.ds@prodoc.lk",
    years_of_experience: "12",
    image_url: "Dr.Mihiri.jpeg",
    associated_hospitals: '[{"name":"Kings Hospital","type":"Private"},{"name":"Asiri Central Hospital ","type":"Private"}]',
    bio: "Dr. Mihiri de Silva focuses on adolescent and adult psychiatry, delivering empathetic care and evidence-based treatment plans.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Psychiatry), Diploma in Child & Adolescent Psychiatry"
  },
  {
    doctor_id: "48",
    full_name: "Dr. Pradeep Kumara",
    slmc_number: "SLMC-MD-1027",
    specialty: "Cardiologist",
    gender: "Male",
    department_type: "Both",
    working_hospital: "Asiri Surgical",
    contact_email: "pradeep.k@prodoc.lk",
    years_of_experience: "18",
    image_url: "Dr.Pradeep.jpeg",
    associated_hospitals: '[{"name":"Asiri Surgical","type":"Private"},{"name":"Durdans Hospital ","type":"Private"}]',
    bio: "Dr. Pradeep Kumara specializes in interventional cardiology and cardiac risk assessment, offering advanced diagnostic and therapeutic procedures.",
    languages: "English, Sinhala, Tamil",
    second_opinion_available: "true",
    second_opinion_dates: "Wed,Sat,Sun",
    educational_qualifications: "MBBS, MD (Cardiology), Fellowship in Interventional Cardiology"
  },
  {
    doctor_id: "49",
    full_name: "Dr. Kumari Fernando",
    slmc_number: "SLMC-MD-1028",
    specialty: "Cardiologist",
    gender: "Female",
    department_type: "Both",
    working_hospital: "Durdans Hospital",
    contact_email: "kumari.f@prodoc.lk",
    years_of_experience: "20",
    image_url: "Dr.Kumari.jpeg",
    associated_hospitals: '[{"name":"Durdans Hospital","type":"Private"},{"name":"Hemas Hospital ","type":"Private"}]',
    bio: "Dr. Kumari Fernando is dedicated to preventive cardiology and the management of hypertension, heart disease, and lipid disorders.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Thu,Fri",
    educational_qualifications: "MBBS, MD (Cardiology), FRCP (London)"
  },
  {
    doctor_id: "50",
    full_name: "Dr. Jagath Munasinghe",
    slmc_number: "SLMC-MD-1031",
    specialty: "Orthopedic Surgeon",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Asiri Central",
    contact_email: "jagath.m@prodoc.lk",
    years_of_experience: "25",
    image_url: "Dr.Jagath.jpeg",
    associated_hospitals: '[{"name":"Asiri Central Hospital","type":"Private"},{"name":"Hemas Hospital ","type":"Private"}]',
    bio: "Dr. Jagath Munasinghe provides expert care in fracture management, joint surgery, and musculoskeletal rehabilitation.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MS (Orthopedic Surgery), FRCS (Edinburgh)"
  },
  {
    doctor_id: "51",
    full_name: "Dr. Shashi Prabha",
    slmc_number: "SLMC-MD-1032",
    specialty: "Orthopedic Surgeon",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Hemas Hospital",
    contact_email: "shashi.p@prodoc.lk",
    years_of_experience: "8",
    image_url: "Dr.Shashi.jpeg",
    associated_hospitals: '[{"name":"Hemas Hospital","type":"Private"}]',
    bio: "Dr. Shashi Prabha specializes in minimally invasive orthopedic procedures and sports injury management to restore patient mobility.",
    languages: "English, Tamil",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Thu,Sat",
    educational_qualifications: "MBBS, MS (Orthopedic Surgery)"
  },
  {
    doctor_id: "52",
    full_name: "Dr. Roshantha Alwis",
    slmc_number: "SLMC-MD-1033",
    specialty: "Pediatrician",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Ninewells Hospital",
    contact_email: "roshantha.a@prodoc.lk",
    years_of_experience: "15",
    image_url: "Dr.Roshantha.jpeg",
    associated_hospitals: '[{"name":"Ninewells Hospital","type":"Private"}]',
    bio: "Dr. Roshantha Alwis offers comprehensive pediatric care including immunizations, growth monitoring, and management of childhood illnesses.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Pediatrics), Diploma in Child Health"
  },
  {
    doctor_id: "53",
    full_name: "Dr. Dilshani Gomes",
    slmc_number: "SLMC-MD-1034",
    specialty: "Pediatrician",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Lanka Hospitals",
    contact_email: "dilshani.g@prodoc.lk",
    years_of_experience: "10",
    image_url: "Dr.Dilshani.jpeg",
    associated_hospitals: '[{"name":"Lanka Hospitals","type":"Private"}]',
    bio: "Dr. Dilshani Gomes focuses on preventive pediatrics, nutrition guidance, and developmental assessments to ensure healthy child growth.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Pediatrics)"
  },
  {
    doctor_id: "54",
    full_name: "Dr. Nuwan Kulatunga",
    slmc_number: "SLMC-MD-1035",
    specialty: "Gynaecologist",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Castle Street Hospital",
    contact_email: "nuwan.k@prodoc.lk",
    years_of_experience: "14",
    image_url: "Dr.Nuwan.jpeg",
    associated_hospitals: '[{"name":"Castle Street Hospital","type":"Government"}]',
    bio: "Dr. Nuwan Kulatunga provides expert obstetric and gynecological services, including prenatal care and surgical management of gynecological conditions.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Wed,Fri",
    educational_qualifications: "MBBS, MD (Obstetrics & Gynaecology)"
  },
  {
    doctor_id: "55",
    full_name: "Dr. Iresha Jayawardena",
    slmc_number: "SLMC-MD-1036",
    specialty: "Gynaecologist",
    gender: "Female",
    department_type: "Government",
    working_hospital: "De Soysa Hospital",
    contact_email: "iresha.j@prodoc.lk",
    years_of_experience: "19",
    image_url: "Dr.Iresha.jpeg",
    associated_hospitals: '[{"name":"De Soysa Hospital","type":"Government"}]',
    bio: "Dr. Iresha Jayawardena specializes in women’s reproductive health, fertility treatment, and minimally invasive gynecological procedures.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Obstetrics & Gynaecology), Fellowship in Maternal-Fetal Medicine"
  },
  {
    doctor_id: "56",
    full_name: "Dr. Thushara Bandara",
    slmc_number: "SLMC-MD-1037",
    specialty: "General Physician",
    gender: "Male",
    department_type: "Government",
    working_hospital: "Kurunegala TH",
    contact_email: "thushara.b@prodoc.lk",
    years_of_experience: "21",
    image_url: "Dr.Thushara.jpeg",
    associated_hospitals: '[{"name":"Kurunegala TH"}]',
    bio: "Dr. Thushara Bandara delivers comprehensive internal medicine care, managing chronic diseases and promoting preventive health strategies.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Fri,Sat",
    educational_qualifications: "MBBS, MD (Internal Medicine), MRCP"
  },
  {
    doctor_id: "57",
    full_name: "Dr. Menaka Edirisinghe",
    slmc_number: "SLMC-MD-1038",
    specialty: "General Physician",
    gender: "Female",
    department_type: "Government",
    working_hospital: "TH Peradeniya",
    contact_email: "menaka.e@prodoc.lk",
    years_of_experience: "9",
    image_url: "Dr.Menaka.jpeg",
    associated_hospitals: '[{"name":"TH Peradeniya"}]',
    bio: "Dr. Menaka Edirisinghe focuses on holistic primary care, early disease detection, and long-term management of metabolic and cardiovascular conditions.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Mon,Wed,Sun",
    educational_qualifications: "MBBS, MD (Internal Medicine)"
  },
  {
    doctor_id: "58",
    full_name: "Dr. Amal Senanayake",
    slmc_number: "SLMC-MD-1039",
    specialty: "Radiologist",
    gender: "Male",
    department_type: "Private",
    working_hospital: "Durdans Hospital",
    contact_email: "amal.s@prodoc.lk",
    years_of_experience: "17",
    image_url: "Dr.Amal.jpeg",
    associated_hospitals: '[{"name":"Durdans Hospital"}]',
    bio: "Dr. Amal Senanayake is a consultant radiologist skilled in advanced imaging interpretation, supporting accurate diagnosis through CT, MRI, ultrasound, and X-ray services.",
    languages: "English, Sinhala",
    second_opinion_available: "true",
    second_opinion_dates: "Tue,Thu",
    educational_qualifications: "MBBS, MD (Radiology), Fellowship in Imaging"
  },
  {
    doctor_id: "59",
    full_name: "Dr. Pavithra Karunaratne",
    slmc_number: "SLMC-MD-1040",
    specialty: "Radiologist",
    gender: "Female",
    department_type: "Private",
    working_hospital: "Asiri Medical",
    contact_email: "pavithra.k@prodoc.lk",
    years_of_experience: "6",
    image_url: "Dr.Pavithra.jpeg",
    associated_hospitals: '[{"name":"Asiri Medical"}]',
    bio: "Dr. Pavithra Karunaratne specializes in diagnostic and interventional radiology, contributing to precise imaging-guided procedures and patient-centered care.",
    languages: "English, Sinhala",
    second_opinion_available: "false",
    educational_qualifications: "MBBS, MD (Radiology)"
  }
];
